force-app/main/default/objects/PropostaCompra__c/PropostaCompra__c.object-meta.xml
<CustomObject>
    <label>Proposta de compra</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Proposta de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propostas de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropostaCompra__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Campo que representa a data da proposta de compra</description>
    <inlineHelpText>Data da proposta de compra</inlineHelpText>
    <label>Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Aguardando</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Reprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch/ReprovaPropostaMaisDe40DStatusAgPgBatch.cls
public with sharing class ReprovaPropostaMaisDe40DStatusAgPgBatch implements Database.Batchable<sObject>{

    public Database.QueryLocator start(Database.BatchableContext bc){

        Date data = System.today() - 40;
        return Database.getQueryLocator([SELECT Id,  Status__c, Data__c
                                         FROM PropostaCompra__c
                                        WHERE Status__c = 'Aguardando pagamento'
                                         AND Data__c < :data]);
    }

    public  void execute(Database.BatchableContext bc, List<PropostaCompra__c> propostaList){


        PropostaCompraBO.getInstance().reprovaPropostaMaisDe40Dias(propostaList);
    }

    public void finish(Database.BatchableContext bc){
    }
   
}