force-app/main/default/objects/Imovel__c/Imovel__c.object-meta.xml
<CustomObject>
    <description>Objeto que possui as informações dos imóveis.</description>
    <label>Imóvel</label>
    <nameField>
        <displayFormat>IMV-{00000}</displayFormat>
        <label>Imóvel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imovel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponível</fullName>
                <default>true</default>
                <label>Disponível</label>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/PropostaCompra__c.object-meta.xml
<CustomObject>
    <label>Proposta de compra</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Proposta de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propostas de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropostaCompra__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Propostas de compra</relationshipLabel>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Imovel__c.field-meta.xml
<CustomField>
    <fullName>Imovel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Imóvel</label>
    <referenceTo>Imovel__c</referenceTo>
    <relationshipLabel>Propostas de compra</relationshipLabel>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Aguardando</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Reprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <inlineHelpText>Valor da Proposta</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ImovelController.cls
public with sharing class ImovelController {
    @AuraEnabled
    public static List<ImovelTO> ultimas5VendasImovel(){

        List<ImovelTO> lstImovelTO = new List<ImovelTO>();

        try{

            List<PropostaCompra__c> listaProposta = [SELECT LastModifiedDate, Valor__c, Contact__r.Name, Imovel__r.Name, Vendedor__r.Name, Imovel__r.RecordType.Name, Imovel__r.id,Contact__r.Id
                                                    FROM PropostaCompra__c                       
                                                    WHERE Status__c = 'Finalizada' 
                                                    ORDER BY LastModifiedDate DESC NULLS LAST LIMIT 5];
                                           
            for (PropostaCompra__c p : listaProposta ){
                    ImovelTO to = new ImovelTO();
                    to.id = p.Imovel__r.id;
                    to.numeroImovel = p.Imovel__r.Name;
                    to.tipoImovel = p.Imovel__r.RecordType.Name;
                    to.nomeCliente = p.Contact__r.Name;
                    to.idCliente = p.Contact__r.Id;
                    to.valorVenda = p.Valor__c;
                    to.vendedor = p.Vendedor__r.Name;
                    lstImovelTO.add(to);
                

            }

            return lstImovelTO;

        } catch (Exception e){

            throw new AuraHandledException(e.getMessage());

        }

        
    }   
}