force-app/main/default/objects/Comissao__c/Comissao__c.object-meta.xml
<CustomObject>
    <label>Comissão</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissões</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comissao__c/fields/PropostaCompra__c.field-meta.xml
<CustomField>
    <fullName>PropostaCompra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta de compra</label>
    <referenceTo>PropostaCompra__c</referenceTo>
    <relationshipLabel>Comissões</relationshipLabel>
    <relationshipName>Comissoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comissao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em pagamento</fullName>
                <default>true</default>
                <label>Em pagamento</label>
            </value>
            <value>
                <fullName>Paga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracaoPropostaCompra__mdt/ConfiguracaoPropostaCompra__mdt.object-meta.xml
<CustomObject>
    <label>Configuração proposta de compra</label>
    <pluralLabel>Configurações propostas de compras</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoPropostaCompra__mdt/fields/DiasEntregaChavesMetadata__c.field-meta.xml
<CustomField>
    <fullName>DiasEntregaChavesMetadata__c</fullName>
    <label>Dias para entrega de chaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPropostaCompra__mdt/fields/PercentualComissao__c.field-meta.xml
<CustomField>
    <fullName>PercentualComissao__c</fullName>
    <label>Percentual de comissão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPropostaCompra__mdt/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartamento</fullName>
                <default>true</default>
                <label>Apartamento</label>
            </value>
            <value>
                <fullName>Casa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imovel__c/Imovel__c.object-meta.xml
<CustomObject>
    <description>Objeto que possui as informações dos imóveis.</description>
    <label>Imóvel</label>
    <nameField>
        <displayFormat>IMV-{00000}</displayFormat>
        <label>Imóvel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imovel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponível</fullName>
                <default>true</default>
                <label>Disponível</label>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/PropostaCompra__c.object-meta.xml
<CustomObject>
    <label>Proposta de compra</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Proposta de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propostas de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropostaCompra__c/fields/DataEntregaChaves__c.field-meta.xml
<CustomField>
    <fullName>DataEntregaChaves__c</fullName>
    <label>Data da entrega das chaves</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Imovel__c.field-meta.xml
<CustomField>
    <fullName>Imovel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Imóvel</label>
    <referenceTo>Imovel__c</referenceTo>
    <relationshipLabel>Propostas de compra</relationshipLabel>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Aguardando</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Reprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <inlineHelpText>Valor da Proposta</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BO/PropostaCompraBO.cls
public with sharing class PropostaCompraBO{
    private static PropostaCompraBO instance = new PropostaCompraBO();
    public static PropostaCompraBO getInstance(){
        return instance;
    }

    public void criaComissaoPropostaStatusAgPagamento(List<PropostaCompra__c> lstPropostas){

        Map<String, ConfiguracaoPropostaCompra__mdt> mapCpc = new Map<String, ConfiguracaoPropostaCompra__mdt>();
        List<Comissao__c> criarComissao = new List<Comissao__c>();
        set<id> propostaListid = new set<id>();
        set<id> imovelId = new set<id>();
        Map<Id, Imovel__c> imovelMap = new Map<Id, Imovel__c>();
        //map para identificar se já existe uma comissão para essa proposta,
        //caso tenha não a comissão não será criada.
        Map<Id, Comissao__c> mapComissao = new Map<Id, Comissao__c>();

        for (ConfiguracaoPropostaCompra__mdt cpc : [SELECT id, Tipo__c, PercentualComissao__c, Label
                                                    FROM ConfiguracaoPropostaCompra__mdt]){
            mapCpc.put(cpc.Label, cpc);
        }

        for (PropostaCompra__c p : lstPropostas){
            imovelId.add(p.Imovel__c);
            propostaListid.add(p.Id);
        }

        for (Imovel__c i : ImovelDAO.getPropostaCompraIdList(imovelId)){
            imovelMap.put(i.Id, i);

        }

        for (Comissao__c c : ComissaoDAO.getPropostaCompraIdList(propostaListid)){
            mapComissao.put(c.PropostaCompra__C, c);
        }

        for (PropostaCompra__c p : lstPropostas){
            //valida se ja existe comissão para essa proposta.
            if (mapComissao.containsKey(p.id)){

                continue;
            }
            //System.debug('#######################' + p.Status__c);
            if (p.Status__c == 'Aguardando pagamento'){
                Comissao__c c = new Comissao__c();
                c.OwnerId = p.Vendedor__c;
                c.PropostaCompra__c = p.Id;
                //System.debug(p.Imovel__r.RecordType.Name);
                //pegando o nome do tipo do registro do imovel
                String rtNameImovel = imovelMap.get(p.Imovel__c).RecordType.Name;
                //pegrando o tipo de percentual de comissão para o tipo de registro do imovel
                Decimal porcentagem = mapCpc.get(rtNameImovel).PercentualComissao__c;
                //System.debug(porcentagem);
                c.Valor__c = (p.Valor__c * porcentagem) / 100;
                c.Status__c = 'Em pagamento';

                criarComissao.add(c);
                // System.debug('############LISTA COMISSÃO##############');
                //System.debug(c);
            }
        }
        //System.debug('#############Lista COmissoes#############');
        //System.debug(criarComissao);
        Database.insert (criarComissao);
    }

    public void preencheDataEntregaChaves(List<PropostaCompra__c> lstPropostas){
        set<id> imovelId = new set<id>();
        set<id> propostaListid = new set<id>();
        Map<Id, Imovel__c> imovelMap = new Map<Id, Imovel__c>();
        Map<String, ConfiguracaoPropostaCompra__mdt> mapCpcTipoImovel = new Map<String, ConfiguracaoPropostaCompra__mdt>();
        for (ConfiguracaoPropostaCompra__mdt cpc : [SELECT id, Tipo__c, PercentualComissao__c, Label, DiasEntregaChavesMetadata__c
                                                    FROM ConfiguracaoPropostaCompra__mdt]){
            mapCpcTipoImovel.put(cpc.Label, cpc);
        }

        for (PropostaCompra__c p : lstPropostas){
            imovelId.add(p.Imovel__c);
            propostaListid.add(p.Id);
        }

        for (Imovel__c i : ImovelDAO.getPropostaCompraIdList(imovelId)){
            imovelMap.put(i.Id, i);
        }
        for (PropostaCompra__c p : lstPropostas){

            if (p.Status__c == 'Finalizada'){
                String tipo = imovelMap.get(p.Imovel__c).RecordType.Name;
                //System.debug('###>>>>> TIPO');
                //System.debug(tipo);
                Integer prazo = (Integer) mapCpcTipoImovel.get(tipo).DiasEntregaChavesMetadata__c;
                //System.debug('####>>>>>>PRAZO');
                //System.debug(prazo);
                p.DataEntregaChaves__c = System.today() + prazo;
            }
        }
    }

    public void reprovaPropostaMaisDe40Dias(List<PropostaCompra__c> propostaList){

        for(PropostaCompra__c p : propostaList){
           
                p.Status__c = 'Reprovada';
          
            
        }
        //System.debug('###>>>>>>LISTA');
        //System.debug(propostaList);
        Database.update(propostaList);
    }
}