force-app/main/default/objects/Comissao__c/Comissao__c.object-meta.xml
<CustomObject>
    <label>Comissão</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissões</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comissao__c/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <formula>IF(  PropostaCompra__r.Imovel__r.RecordType.DeveloperName == &apos;Apartamento&apos;, 
					 $CustomMetadata.ConfiguracaoPropostaCompra__mdt.Apartamento.PercentualComissao__c , 
		$CustomMetadata.ConfiguracaoPropostaCompra__mdt.Casa.PercentualComissao__c 			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Comissao__c/fields/PropostaCompra__c.field-meta.xml
<CustomField>
    <fullName>PropostaCompra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta de compra</label>
    <referenceTo>PropostaCompra__c</referenceTo>
    <relationshipLabel>Comissões</relationshipLabel>
    <relationshipName>Comissoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comissao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em pagamento</fullName>
                <default>true</default>
                <label>Em pagamento</label>
            </value>
            <value>
                <fullName>Paga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imovel__c/Imovel__c.object-meta.xml
<CustomObject>
    <description>Objeto que possui as informações dos imóveis.</description>
    <label>Imóvel</label>
    <nameField>
        <displayFormat>IMV-{00000}</displayFormat>
        <label>Imóvel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imovel__c/fields/Metragem__c.field-meta.xml
<CustomField>
    <fullName>Metragem__c</fullName>
    <inlineHelpText>Metragem do empreendimento em m2</inlineHelpText>
    <label>Metragem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imovel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponível</fullName>
                <default>true</default>
                <label>Disponível</label>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imovel__c/fields/ValorBase__c.field-meta.xml
<CustomField>
    <fullName>ValorBase__c</fullName>
    <label>Valor base</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/PropostaCompra__c.object-meta.xml
<CustomObject>
    <label>Proposta de compra</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Proposta de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propostas de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropostaCompra__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Propostas de compra</relationshipLabel>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Imovel__c.field-meta.xml
<CustomField>
    <fullName>Imovel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Imóvel</label>
    <referenceTo>Imovel__c</referenceTo>
    <relationshipLabel>Propostas de compra</relationshipLabel>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Aguardando</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Reprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <inlineHelpText>Valor da Proposta</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DAO/PropostaCompraDAO.cls
public with sharing class PropostaCompraDAO {
    public static List<PropostaCompra__c> getPropostaCompraIdList(set<Id> propostaId){
        return [SELECT id, Status__c FROM PropostaCompra__c WHERE id  IN: propostaId];
    }

    public static PropostaCompra__c getPropostaCompra(String recordId){

        return [SELECT LastModifiedDate, Valor__c, Name, Contact__r.Name, Imovel__r.Name, Vendedor__r.Name, 
                Imovel__r.RecordType.Name, Imovel__r.Metragem__c, Imovel__r.ValorBase__c , Imovel__r.id,Contact__r.Id,
                (SELECT id, Percentual__c, 	Valor__c, Name FROM Comissoes__r)
                FROM PropostaCompra__c                       
                WHERE Id =:recordId
                LIMIT 1];

    }
}