force-app/main/default/objects/Comissao__c/Comissao__c.object-meta.xml
<CustomObject>
    <label>Comissão</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissões</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comissao__c/fields/PropostaCompra__c.field-meta.xml
<CustomField>
    <fullName>PropostaCompra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta de compra</label>
    <referenceTo>PropostaCompra__c</referenceTo>
    <relationshipLabel>Comissões</relationshipLabel>
    <relationshipName>Comissoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comissao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em pagamento</fullName>
                <default>true</default>
                <label>Em pagamento</label>
            </value>
            <value>
                <fullName>Paga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imovel__c/Imovel__c.object-meta.xml
<CustomObject>
    <description>Objeto que possui as informações dos imóveis.</description>
    <label>Imóvel</label>
    <nameField>
        <displayFormat>IMV-{00000}</displayFormat>
        <label>Imóvel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imovel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponível</fullName>
                <default>true</default>
                <label>Disponível</label>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/PropostaCompra__c.object-meta.xml
<CustomObject>
    <label>Proposta de compra</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Proposta de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propostas de compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropostaCompra__c/fields/Imovel__c.field-meta.xml
<CustomField>
    <fullName>Imovel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Imóvel</label>
    <referenceTo>Imovel__c</referenceTo>
    <relationshipLabel>Propostas de compra</relationshipLabel>
    <relationshipName>Propostas_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PropostaCompra__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Aguardando</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Reprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BO/ComissaoBO.cls
public with sharing class ComissaoBO{

    private static ComissaoBO instance = new ComissaoBO();

    public static ComissaoBO getInstance(){
        return instance;
    }

    public void attStatusComissao(List<PropostaCompra__c> lstPropsta){

        //proposta de compra onde o status esteja como finalizada o
        //Status da comissão vai para Paga e e status do ímovel vai para Vendido
        List<Imovel__c> attImoveisStatus = new List<Imovel__c>();

        set<id> propostaListid = new set<id>();

        for(PropostaCompra__c p : lstPropsta){
            if(p.Status__c == 'Finalizada'){
                propostaListid.add(p.Id);
                Imovel__c i = new Imovel__c();
                i.Id = p.Imovel__c;
                i.Status__c = 'Vendido';
                attImoveisStatus.add(i);
            }
        }

        Database.update(attImoveisStatus);

        List<Comissao__c> listComissao = ComissaoDAO.getPropostaCompraIdList(propostaListid);

        if(listComissao.size() >0){
            for(Comissao__c c : listComissao){
                c.Status__c = 'Paga';
            }
        }


        Database.update(listComissao);
    }

}